# Generated by Django 5.0.4 on 2024-04-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entry_title", models.CharField(max_length=256)),
                ("image", models.BinaryField()),
                ("entry", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "general_entry_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.generalentry",
                    ),
                ),
            ],
        ),
    ]
