# Generated by Django 5.0.4 on 2024-04-22 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookEntry",
        ),
        migrations.DeleteModel(
            name="GeneralEntry",
        ),
    ]
